language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install
script: grunt -v
branches:
    except:
      - gh-pages
sudo: false
before_install:
  - npm config set registry https://:2016-05-02T17%3A09%3A58.461000Z@time-machines-npm.sealsecurity.io/
dist: precise
